[~] change parsing -> backup

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -16,7 +16,7 @@ on:
 jobs:
   # Verif coding:
   check_coding_style:
-    name: "Annotations"
+    name: "🕵️‍♀️ Check the Coding_Style 🕵️‍♀️"
     runs-on: ubuntu-latest
     container:
       image: ghcr.io/epitech/coding-style-checker:latest
@@ -25,23 +25,25 @@ jobs:
         uses: actions/checkout@v3.4.0
       - name: Check coding style
         run: |
-          ./check.sh $(pwd) $(pwd)
+          ./check.sh $(pwd) $(pwd) > coding-style-reports.log 2>&1 || true
       - name: Display error log file details
         run: ls -l coding-style-reports.log
       - name: Display errors as annotations
         if: always()
         run: |
-          if [ -f coding-style-reports.log ]; then
-            while IFS= read -r line; do
-                file="$(echo "$line" | cut -d ':' -f 1)"
-                line_number="$(echo "$line" | cut -d ':' -f 2)"
-                message="$(echo "$line" | cut -d ':' -f 3)"
-                error_code="$(echo "$line" | cut -d ':' -f 4)"
-                annotation="[${error_code}] ${message}"
-                echo "::error file=${file},line=${line_number}::${annotation}"
-            done < coding-style-reports.log
-          fi
-
+          set -e
+          echo "coucou"
+          while IFS= read -r line; do
+           if [[ $line =~ ^(MINOR|MAJOR|)$ ]]; then
+              echo "coucouuu"
+              file="${BASH_REMATCH[2]}"
+              line_number="${BASH_REMATCH[3]}"
+              message="${BASH_REMATCH[4]}"
+              error_code="${BASH_REMATCH[5]}"
+              annotation="[${BASH_REMATCH[1]} coding style error] ${message} (${error_code})"
+              echo "::error file=${file},line=${line_number}::${annotation}"
+            fi
+          done < coding-style-reports.log
       - name: Fail if there are errors
         run: |
           if [ -s coding-style-reports.log ]
